
[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "flash-sparse-attn"
dynamic = ["version"]
description = "Flash Sparse Attention: Fast and Memory-Efficient Trainable Sparse Attention"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Jingze Shi", email = "losercheems@gmail.com" },
  { name = "Yifan Wu", email = "ywu012@connect.hkust-gz.edu.cn" },
  { name = "Bingheng Wu", email = "wubingheng52136@gmail.com" },
  { name = "Yiran Peng", email = "amagipeng@gmail.com" },
  { name = "Liangdong Wang", email = "wangliangdong@baai.ac.cn" },
  { name = "Guang Li", email = "liuguang@baai.ac.cn" },
  { name = "Yuyu Luo", email = "yuyuluo@hkust-gz.edu.cn" }
]
maintainers = [
  { name = "Jingze Shi", email = "losercheems@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
  "triton>=3.6.0",
  "triton_kernels @ git+https://github.com/triton-lang/triton.git@v3.6.0#subdirectory=python/triton_kernels"
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: BSD License",
  "Operating System :: Unix"
]

[project.urls]
Homepage = "https://github.com/HKUSTDial/flash-sparse-attention"
Source = "https://github.com/HKUSTDial/flash-sparse-attention"
Issues = "https://github.com/HKUSTDial/flash-sparse-attention/issues"

[project.optional-dependencies]
cute = [
  "nvidia-cutlass-dsl>=4.4.2",
  "einops",
  "typing_extensions",
  "apache-tvm-ffi>=0.1.5,<0.2",
  "torch-c-dlpack-ext",
  "quack-kernels>=0.3.3"
]
dev = [
  "transformers>=4.38.0",
  "pytest>=6.0",
  "pytest-benchmark",
  "numpy",
  "tabulate>=0.9.0"
]
docs = [
  "mkdocs>=1.6",
  "mkdocs-material>=9.5",
  "mkdocstrings[python]>=0.28",
  "pymdown-extensions>=10.0"
]

[tool.setuptools.dynamic]
version = { attr = "flash_sparse_attn.__version__" }

[tool.setuptools.packages.find]
where = ["."]
include = ["flash_sparse_attn*"]
exclude = [
  "docs",
]

[tool.setuptools.package-data]
flash_sparse_attn = ["*.py"]

[tool.setuptools]
